### ISSUE TITLE
[ Help ]The BinanceBot Exception : ValueError: 0 is not in range

### ISSUE THREAD

**Issue by honsaun** [DaScient/SuperTrendTradingBot#3]
python3 binance_bot.py
Input a name: OPTIMUS
Insert ticker: OPTIMUS
Enter denomination (examples: USD, USDT, BUSD, BTC): USDT
Candlestick intervals (1m,5m,15m,30m,1h,2h,6h,1d): 1m
Order size in OPTIMUS: 300
Already in desired holding position? - True/False: False
Min gain: %3
Loading...
Please allow for 1m until initial results are printed.

##~##  ┌( ಠ_ಠ)┘  ##~##
2023-04-15T00:35:10.810584+08:00
Generating market indications for OPTIMUS.

Calculating OPTIMUS/USDT data...
                    timestamp  volume  in_uptrend
146 2023-04-14 16:32:00-07:00   80.00       False
147 2023-04-14 16:33:00-07:00    0.00       False
148 2023-04-14 16:34:00-07:00   18.01       False

Open: 0.5176    Max low: 0.5331279999999999
High: 0.5176    Minimum sell price: 0.5176
Low: 0.5162     Timeframe: 1m
Close: 0.5162   Safe sell: False
Mini-timeframe  uptrend  identified - buying signal: True

Mini-timeframe downtrend identified - selling signal: False
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 345, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lighthouse/mexcSuperTrend/binance_bot.py", line 401, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.10/dist-packages/schedule/__init__.py", line 822, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.10/dist-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.10/dist-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.10/dist-packages/schedule/__init__.py", line 693, in run
    ret = self.job_func()
  File "/home/lighthouse/mexcSuperTrend/binance_bot.py", line 387, in run_bot
    bal = bal[bal['asset']==ticker[:4].replace('/','')].reset_index(drop = True).free[0]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/series.py", line 1012, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/series.py", line 1121, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 347, in get_loc
    raise KeyError(key) from err
KeyError: 0

**How can i fix it ? sir**

**Comment by DaScient** [comment]
Binance recently updated three endpoints on the Binance.US API Documentation portal that allow API traders to convert small balances and crypto dust.Binance.US previously supported conversions of small balances and crypto dust with a value under $20 into BTC. This update expands this feature to include Bitcoin (BTC), Ethereum (ETH), and USD. The updated endpoints include:
--
updated three endpoints on the [Binance.US API Documentation](https://clicks.binance.us/ls/click?upn=ykzTgymme2AEbkv-2BVDX4n9pWrmipsIpryiEmWKTgHEJ8-2F5IjNotVQhyPfm3DNnpIgMyWxiv8wViSwZ9TXUonXEiSyFOD1nn-2BjGt160LXjUTNsVRzmjxY8dD00TnQfTeWCgiGrOxVyNcA7Ffk7RZhgno0dy23kY38yIhuawqpkqiVA-2BR4hgpxF1w029ZXXDqlzIXG_e4l1skY0aRwq8jEam6gPSbke1IMh5f3NL0onG8Vp4nfhxgyLHsTdpUCmmqJROrO6c7xovL1oybPLNdbaHqx1vgZq2leLi7EgUVR6kTGCCT9mt4gIUS5zsAgYVcHz4yAjbt4mY62EAQnKfGkS2WZldzGJzTUO6L-2BACC2Q8IwNHz0FzYT3wS8TzO5VnOwN2-2F6tO9HrWI-2FxF9lNFjD1Czi4yW8KanW-2FDdV56ejR1yG-2FeVJJS6ThAQ4kMfVwOcTET-2BkYlRlTcTeF0OH4UGtgFmQcPpsSiES6q40L2bTIqngbZlTkWLd-2B12wdyDO0lNnZLR-2B8pwBapzckzpb49MSf-2FiyMxZR035ubu3jGUGzNW0L8shUbM98AdFU6990XHByHfiDL0mpsFys3sKApkl3r5NF55QBJYL-2F9wZV92-2FPQuO1OgkD-2Ftq-2BVQUU4-2BSNDW-2F5-2BQFEBRtBSj5sPWgxTvbNM6-2FHV3aDf-2FOtUilucrAhKylHrJj9JXZxtGuwMwUeqvvOV5sNir1HY-2FAKmhDFBMEVY9Bn-2F0p45GVY7WCbtjTeP8yIGsyiDJMuJIn2w2t-2FofxzhLzyaCpdk55Jz-2FB41zTD6tm11iYgx5RTTSTVG0Sbxv-2B7z0tcNOXIrNPPPPITkHrP-2BFaVpPkfNJy2GnVbRoXVS0zJKuNHEtZ3oorZTJoBDc1he7Twunrqsx-2BNt7qEMpTps5dHHu3IL6jCKDm09No1XNeVxNCmXRfbHj2KvFXqby5lVmow-3D) portal that allow API traders to convert small balances and crypto dust.

Binance.US previously supported [conversions of small balances](https://clicks.binance.us/ls/click?upn=ykzTgymme2AEbkv-2BVDX4n9pWrmipsIpryiEmWKTgHEJznsXrLKpSTldKSR0cArWFw87R2sx-2FkOx9io83CaOuC4TFSq0b4Yg4IJ4rpW-2F2ZhE-3DinXy_e4l1skY0aRwq8jEam6gPSbke1IMh5f3NL0onG8Vp4nfhxgyLHsTdpUCmmqJROrO6c7xovL1oybPLNdbaHqx1vgZq2leLi7EgUVR6kTGCCT9mt4gIUS5zsAgYVcHz4yAjbt4mY62EAQnKfGkS2WZldzGJzTUO6L-2BACC2Q8IwNHz0FzYT3wS8TzO5VnOwN2-2F6tO9HrWI-2FxF9lNFjD1Czi4yW8KanW-2FDdV56ejR1yG-2FeVJJS6ThAQ4kMfVwOcTET-2BkYlRlTcTeF0OH4UGtgFmQcPpsSiES6q40L2bTIqngbZlTkWLd-2B12wdyDO0lNnZLR-2B8pwBapzckzpb49MSf-2FiyMxZR035ubu3jGUGzNW0L8shUbM98AdFU6990XHByHfiDL0mpsFys3sKApkl3r5NF55QBJYL-2F9wZV92-2FPQuO1OgkD-2Ftq-2BVQUU4-2BSNDW-2F5-2BQFEBRtBSj5sPWgxTvbNM6-2FHV3aDf-2FOtUilucrAhKylHrJj9JXZxtGuwMwUeqvvOV5sNir1HY-2FAKmhDFBMEVY9Bn-2F0p45GVY7WCbtjTeP8yIGsyiDJMuJIn2w2t-2FofxzhLzyaCpdk55Jz-2FB41zTD6tm11iXdtqNw8qHtmxXfRJrdLfPJ6PwLp6BC1mfYdUq3h7WFguJHmWwgrOihqxaj5xNNJ34sY-2BT8ntQaupmU1eVMSI-2BQkOe9OrLi7Hh3r99ZxkAg2synl2KSd9rgga54-2Fi2qJf3vgTx8IMKxZ-2F3l8roZaeU8-3D) and crypto dust with a value under $20 into BTC. This update expands this feature to include Bitcoin (BTC), Ethereum (ETH), and USD. The updated endpoints include:
[Convert Dust](https://clicks.binance.us/ls/click?upn=ykzTgymme2AEbkv-2BVDX4n9pWrmipsIpryiEmWKTgHEJ7DttHMKYYdYcWE0hWpXpH9xn-2FMWBcd2hkSdudhcV8BbUf7p-2BiLXCv3ayLsg6fLzs-3DaZwi_e4l1skY0aRwq8jEam6gPSbke1IMh5f3NL0onG8Vp4nfhxgyLHsTdpUCmmqJROrO6c7xovL1oybPLNdbaHqx1vgZq2leLi7EgUVR6kTGCCT9mt4gIUS5zsAgYVcHz4yAjbt4mY62EAQnKfGkS2WZldzGJzTUO6L-2BACC2Q8IwNHz0FzYT3wS8TzO5VnOwN2-2F6tO9HrWI-2FxF9lNFjD1Czi4yW8KanW-2FDdV56ejR1yG-2FeVJJS6ThAQ4kMfVwOcTET-2BkYlRlTcTeF0OH4UGtgFmQcPpsSiES6q40L2bTIqngbZlTkWLd-2B12wdyDO0lNnZLR-2B8pwBapzckzpb49MSf-2FiyMxZR035ubu3jGUGzNW0L8shUbM98AdFU6990XHByHfiDL0mpsFys3sKApkl3r5NF55QBJYL-2F9wZV92-2FPQuO1OgkD-2Ftq-2BVQUU4-2BSNDW-2F5-2BQFEBRtBSj5sPWgxTvbNM6-2FHV3aDf-2FOtUilucrAhKylHrJj9JXZxtGuwMwUeqvvOV5sNir1HY-2FAKmhDFBMEVY9Bn-2F0p45GVY7WCbtjTeP8yIGsyiDJMuJIn2w2t-2FofxzhLzyaCpdk55Jz-2FB41zTD6tm11ifz1e2HxD86n-2FRt-2BrwG4vBEOxGG-2F1iwGtjT2uEOfnSE9naRdUnY5c2CmB-2FHEa8DDAE9C8z9Qe7mbBcqH-2BYMVor0bXV22hWFmHNa2oalHCZG0yjJeC-2FIH7CU5k-2BxkiLVw3vbzmObVjFl1uj-2ForBQ3rvY-3D): Use this endpoint to convert dust to one of the four available assets.
[Get Convert Dust History](https://clicks.binance.us/ls/click?upn=ykzTgymme2AEbkv-2BVDX4n9pWrmipsIpryiEmWKTgHEJ7Y8bjL6jkMjunRWCU5pxXbrAx16aXW1mDvCoS2rmYRbre3XyB1MmBazbssoKB1wttDLHJ-2BVktU3eu2lMKqUIg-R93_e4l1skY0aRwq8jEam6gPSbke1IMh5f3NL0onG8Vp4nfhxgyLHsTdpUCmmqJROrO6c7xovL1oybPLNdbaHqx1vgZq2leLi7EgUVR6kTGCCT9mt4gIUS5zsAgYVcHz4yAjbt4mY62EAQnKfGkS2WZldzGJzTUO6L-2BACC2Q8IwNHz0FzYT3wS8TzO5VnOwN2-2F6tO9HrWI-2FxF9lNFjD1Czi4yW8KanW-2FDdV56ejR1yG-2FeVJJS6ThAQ4kMfVwOcTET-2BkYlRlTcTeF0OH4UGtgFmQcPpsSiES6q40L2bTIqngbZlTkWLd-2B12wdyDO0lNnZLR-2B8pwBapzckzpb49MSf-2FiyMxZR035ubu3jGUGzNW0L8shUbM98AdFU6990XHByHfiDL0mpsFys3sKApkl3r5NF55QBJYL-2F9wZV92-2FPQuO1OgkD-2Ftq-2BVQUU4-2BSNDW-2F5-2BQFEBRtBSj5sPWgxTvbNM6-2FHV3aDf-2FOtUilucrAhKylHrJj9JXZxtGuwMwUeqvvOV5sNir1HY-2FAKmhDFBMEVY9Bn-2F0p45GVY7WCbtjTeP8yIGsyiDJMuJIn2w2t-2FofxzhLzyaCpdk55Jz-2FB41zTD6tm11ib65u9blqomuTNf-2Fb0d13Y-2BdYoDYd5ZB1IJlYT8guhWBtQqVCA6y0plVF7iddL0lHVsloxvlCs3U0ru1TL99DjR2DwMkfvsySk-2BlZrbPdjfgCrnafzdrCGb8VtusFzrVCqIucsvSFgT4Ly7y2jVhB-2Fs-3D): Use this endpoint to get dust conversion history.
[Get Assets That Can Be Converted](https://clicks.binance.us/ls/click?upn=ykzTgymme2AEbkv-2BVDX4n9pWrmipsIpryiEmWKTgHEKWkaqpYijvuCrzk9MGDNz9FqvbA-2FUJJvJSvK6iqzJ39wOhmTC2d5v8T7E8TR2OUxmpClhqqvoKElMxX4eKZhGWQAkD_e4l1skY0aRwq8jEam6gPSbke1IMh5f3NL0onG8Vp4nfhxgyLHsTdpUCmmqJROrO6c7xovL1oybPLNdbaHqx1vgZq2leLi7EgUVR6kTGCCT9mt4gIUS5zsAgYVcHz4yAjbt4mY62EAQnKfGkS2WZldzGJzTUO6L-2BACC2Q8IwNHz0FzYT3wS8TzO5VnOwN2-2F6tO9HrWI-2FxF9lNFjD1Czi4yW8KanW-2FDdV56ejR1yG-2FeVJJS6ThAQ4kMfVwOcTET-2BkYlRlTcTeF0OH4UGtgFmQcPpsSiES6q40L2bTIqngbZlTkWLd-2B12wdyDO0lNnZLR-2B8pwBapzckzpb49MSf-2FiyMxZR035ubu3jGUGzNW0L8shUbM98AdFU6990XHByHfiDL0mpsFys3sKApkl3r5NF55QBJYL-2F9wZV92-2FPQuO1OgkD-2Ftq-2BVQUU4-2BSNDW-2F5-2BQFEBRtBSj5sPWgxTvbNM6-2FHV3aDf-2FOtUilucrAhKylHrJj9JXZxtGuwMwUeqvvOV5sNir1HY-2FAKmhDFBMEVY9Bn-2F0p45GVY7WCbtjTeP8yIGsyiDJMuJIn2w2t-2FofxzhLzyaCpdk55Jz-2FB41zTD6tm11iWwM6llqdjHe8IZ2izd9mw79TkT9ObGQaypJyfRTYIQBBEdxMU4wKCZheI0NS51Ij78A5mZGKlAf7eQNubFhWZflqAVY7sWOAVgedLZmCd-2BgGv8r2ZBgQJoBZHYWlSlmtelidhxy1mQGKjChT-2FG3iXA-3D): Use this endpoint to get your dust assets that can be converted to any of the four available assets.
See the full changelog [here](https://clicks.binance.us/ls/click?upn=ykzTgymme2AEbkv-2BVDX4n9pWrmipsIpryiEmWKTgHEI-2FUADOcE2bIwbcbG-2B5S9D4EbPOJqEO-2FiuXzPw2TJToEg-3D-3DJpZC_e4l1skY0aRwq8jEam6gPSbke1IMh5f3NL0onG8Vp4nfhxgyLHsTdpUCmmqJROrO6c7xovL1oybPLNdbaHqx1vgZq2leLi7EgUVR6kTGCCT9mt4gIUS5zsAgYVcHz4yAjbt4mY62EAQnKfGkS2WZldzGJzTUO6L-2BACC2Q8IwNHz0FzYT3wS8TzO5VnOwN2-2F6tO9HrWI-2FxF9lNFjD1Czi4yW8KanW-2FDdV56ejR1yG-2FeVJJS6ThAQ4kMfVwOcTET-2BkYlRlTcTeF0OH4UGtgFmQcPpsSiES6q40L2bTIqngbZlTkWLd-2B12wdyDO0lNnZLR-2B8pwBapzckzpb49MSf-2FiyMxZR035ubu3jGUGzNW0L8shUbM98AdFU6990XHByHfiDL0mpsFys3sKApkl3r5NF55QBJYL-2F9wZV92-2FPQuO1OgkD-2Ftq-2BVQUU4-2BSNDW-2F5-2BQFEBRtBSj5sPWgxTvbNM6-2FHV3aDf-2FOtUilucrAhKylHrJj9JXZxtGuwMwUeqvvOV5sNir1HY-2FAKmhDFBMEVY9Bn-2F0p45GVY7WCbtjTeP8yIGsyiDJMuJIn2w2t-2FofxzhLzyaCpdk55Jz-2FB41zTD6tm11iSgeUzV8zfohd07IgyPt-2F3sbsWbzBScSMn2kNv515g2klcppJllMUNdmXAcmmVz-2F3rX1Rf2pZNVXtfjWb6cTiyzoZ8XU9RRojLmtRXFWKnFkUSQSkr9MrAYtrOY6st1KSoCICtcTVwIq1bX2KwzBm8k-3D). 

Also, see our note regarding their API updates. 
Due to Binance US having made some important API changes. Certain consequences may impact this notebook's ability to query historical transaction data for USD trading pairs, including trades and orders, that were executed before our system upgrade on February 5, 2023 at 9 p.m. PST / midnight EST.

To query transaction information for historical trades and orders, involving USD trading pairs, executed before the planned system upgrade, we will need to begin using the USD4 symbol. For example: "BTCUSD4". To query transaction information for trades and orders, involving USD trading pairs, executed after the planned system upgrade, we would need to continue using the USD symbol. For example: “BTCUSD”.

[Kaggle Notebook](https://www.kaggle.com/code/dascient/daily-crypto-buy-sell-decision-maker)

Thank you for raising this concern. Will update soon enough.

**Comment by DaScient** [comment]
Please raise again if this does not provide your solution.
